### PR TITLE
Introduced es6 to JS files

### PR DESCRIPTION
**Pull request by yTakkar**

### CODE REVIEW

**Comment by zenflow** [comment]
@yTakkar Hey! Thanks for the PR!

It's better if you make this PR to the official repo: https://github.com/motdotla/dotenv

Also a question: Did you happen to use an automated tool for this conversion?

**Comment by yTakkar** [comment]
No I did it by myself!!
:)

**Comment by zenflow** [comment]
@yTakkar "lebab" might be of interest to you for the future. I've never used it but it looks useful.

Good luck with the PR on motdotla/dotenv !

**Comment by yTakkar** [comment]
Thnx @zenflow 
I'll checkout lebab

**Pull request closed without merging**
